apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ssl
spec:
  selector:
    matchLabels:
      app: nginx-ssl
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-ssl
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 443
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx
        - name: certs
          mountPath: /etc/certs
      volumes:
      - name: conf
        configMap:
          # 前に作成したnginx向けのConfigMap
          name: nginx-conf
      - name: certs
        secret:
          # 直前に作ったSecret
          secretName: ssl
