apiVersion: v1
kind: Pod
metadata:
  name: adapter-example-health
  namespace: default
spec:
  containers:
  - image: mysql
    name: mysql
  # imageは自分で作ったコンテナイメージに置き換え
  - image: brendanburns/mysql-adapter
    name: adapter
