apiVersion: v1
kind: Pod
metadata:
  name: sharded-memcache-ambassador
spec:
  containers:
    # ここにアプリケーションコンテナの設定を入れる。以下は例
    # - name: nginx
    #   image: nginx
    # これ以降アンバサダコンテナの設定
    - name: twemproxy
      image: ganomede/twemproxy
      command: [ "nutcracker", "-c", "/etc/config/nutcracker.yaml", "-v", "7", "-s", "6222" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: twem-config
